// Generated by CozyScript 0.1.1
(function() {
  var app, cli, compile, express, io, nib, redis, redis_client, server, socket_clients, stylus, util;

  express = require('express');

  stylus = require('stylus');

  nib = require('nib');

  util = require('util');

  redis = require('redis');

  cli = require('cli');

  redis_client = redis.createClient();

  app = express();

  server = require('http').createServer(app);

  io = require('socket.io').listen(server);

  socket_clients = [];

  io.sockets.on('connection', function(socket) {
    return socket_clients.push(socket);
  });

  redis_client.on("message", function(channel, message) {
    var socket, _i, _len, _results;
    console.log("redis client channel " + channel + ": " + message);
    _results = [];
    for (_i = 0, _len = socket_clients.length; _i < _len; _i++) {
      socket = socket_clients[_i];
      _results.push(socket.emit('tweet', message.split(':')));
    }
    return _results;
  });

  compile = function(str, path) {
    return stylus(str).set('filename', path).use(nib());
  };

  app.set('views', __dirname + '/views');

  app.set('view engine', 'jade');

  app.set('view options', {
    layout: false
  });

  app.use(express.logger());

  app.use(express.bodyParser());

  app.use(express.cookieParser());

  app.use(express.session({
    secret: "tweetheapmap"
  }));

  app.use(stylus.middleware({
    src: __dirname + '/public',
    compile: compile
  }));

  app.use(express["static"](__dirname + '/public'));

  app.use(function(error, req, res, next) {
    console.log(error);
    return res.send(500, {
      error: util.inspect(error)
    });
  });

  app.get('/', function(req, res) {
    return res.render('index');
  });

  server.listen(8080);

  redis_client.subscribe('tweets');

}).call(this);
